version: '3.8'

x-base: &base
  volumes:
    - ./:/app
    - ./docker_script.sh:/app/docker_script.sh
    - ./models/.insightface:/root/.insightface
    - ./models/.insightface:/app/.insightface
    - ./models/gfpgan:/app/gfpgan
    - ./models:/app/models

    # Outputfolder for TARGET_FOLDER, SOURCE_FOLDER and OUTPUT_FOLDER
    - ./output:/app/output
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  tty: true
  runtime: nvidia

services:
  Deep-Live-Cam:
    <<: *base
    image: docker.io/avgradmin/deep-swap:v0.1.2-cuda-12.2
    build:
      context: .
      dockerfile: docker/Dockerfile.cuda12-2  
    command: ["/bin/bash", "/app/docker_script.sh" ]
